from flask import Flask, jsonify
from flask_cors import CORS
import yfinance as yf
import os 

app = Flask(__name__)

CORS(app, resources={r"/api/*": {"origins": ["http://localhost:3000", "https://stockdata-k09z.onrender.com"]}})


tickers = [
    {"ticker": "AAK.ST", "name": "AAK"},
    {"ticker": "ABB.ST", "name": "ABB Ltd"},
    {"ticker": "ACAD.ST", "name": "Acadia Realty Trust"},
    {"ticker": "ALIF-B.ST", "name": "Alimak Group AB (publ)"},
    {"ticker": "ANOD-B.ST", "name": "Anoto Group AB (publ)"},
    {"ticker": "ADDT-B.ST", "name": "ADDTECH AB (publ)"},
    {"ticker": "AFRY.ST", "name": "AFRY AB (publ)"},
    {"ticker": "ALFA.ST", "name": "Alfa Laval AB (publ)"},
    {"ticker": "ALIG.ST", "name": "Alligator Bioscience AB (publ)"},
    {"ticker": "ALLEI.ST", "name": "Alleima AB"},
    {"ticker": "ALLIGO-B.ST", "name": "Alligo AB (publ)"},
    {"ticker": "ALVO-SDB.ST", "name": "Alvotech"},
    {"ticker": "AMBEA.ST", "name": "Ambea AB (publ)"},
    {"ticker": "APOTEA.ST", "name": "Apotek Hjärtat AB (publ)"},
    {"ticker": "AQ.ST", "name": "AQ Group AB (publ)"},
    {"ticker": "ARP.ST", "name": "Arise AB (publ)"},
    {"ticker": "ARION-SDB.ST", "name": "Arion Banki hf"},
    {"ticker": "ARISE.ST", "name": "Arise AB (publ)"},
    {"ticker": "ARJO-B.ST", "name": "Arjo AB (publ)"},
    {"ticker": "ASKER.ST", "name": "Asker Healthcare Group AB (publ)"},
    {"ticker": "ASMDEE-B.ST", "name": "ASML Holding N.V."},
    {"ticker": "ASSA-B.ST", "name": "ASSA ABLOY AB (publ)"},
    {"ticker": "AZN.ST", "name": "AstraZeneca PLC"},
    {"ticker": "ATCO-A.ST", "name": "Atlas Copco AB (publ)"},
    {"ticker": "ATCO-B.ST", "name": "Atlas Copco AB (publ)"},
    {"ticker": "ATRLJ-B.ST", "name": "Atrium Ljungberg AB (publ)"},
    {"ticker": "ATT.ST", "name": "ATT Investments AB (publ)"},
    {"ticker": "ALIV-SDB.ST", "name": "Avanza Bank Holding AB (publ)"},
    {"ticker": "AZA.ST", "name": "Azelio AB (publ)"},
    {"ticker": "AXFO.ST", "name": "Axfood AB (publ)"},
    {"ticker": "BACTI-B.ST", "name": "Bactiguard Holding AB (publ)"},
    {"ticker": "BEIA-B.ST", "name": "Beijer Alma AB (publ)"},
    {"ticker": "BERG-B.ST", "name": "Bergman & Beving AB (publ)"},
    {"ticker": "BESQAB.ST", "name": "Besqab AB (publ)"},
    {"ticker": "BESQAB-PREF-B.ST", "name": "Besqab AB (publ) Pref"},
    {"ticker": "BETS-B.ST", "name": "Betsson AB (publ)"},
    {"ticker": "BETCO.ST", "name": "Better Collective A/S"},
    {"ticker": "BHG.ST", "name": "Bygghemma Group AB (publ)"},
    {"ticker": "BICO.ST", "name": "BICO Group AB (publ)"},
    {"ticker": "BILI-A.ST", "name": "Bilia AB (publ)"},
    {"ticker": "BILL.ST", "name": "Billie Eilish"},
    {"ticker": "BIOA-B.ST", "name": "BioArctic AB (publ)"},
    {"ticker": "BIOG-B.ST", "name": "Biotage AB (publ)"},
    {"ticker": "BINV.ST", "name": "Bioinvent International AB (publ)"},
    {"ticker": "BOL.ST", "name": "Boliden AB (publ)"},
    {"ticker": "BONAV-A.ST", "name": "Bonnier Fastigheter AB (publ)"},
    {"ticker": "BONAV-B.ST", "name": "Bonnier Fastigheter AB (publ)"},
    {"ticker": "BONEX.ST", "name": "Bonaventura"},
    {"ticker": "BOOZT.ST", "name": "Boozt AB (publ)"},
    {"ticker": "BRAV.ST", "name": "Bravo Group AB (publ)"},
    {"ticker": "BRIN-B.ST", "name": "Brinova Fastigheter AB (publ)"},
    {"ticker": "BTS-B.ST", "name": "BTS Group AB (publ)"},
    {"ticker": "BUFAB.ST", "name": "Bufab AB (publ)"},
    {"ticker": "BURE.ST", "name": "Bure Equity AB (publ)"},
    {"ticker": "BMAX.ST", "name": "Byggmax Group AB (publ)"},
    {"ticker": "AJA-B.ST", "name": "Byggmästare A J Ahlström"},
    {"ticker": "CAMX.ST", "name": "Camurus AB (publ)"},
    {"ticker": "CAST.ST", "name": "Castellum AB (publ)"},
    {"ticker": "CAT-A.ST", "name": "Catella AB (publ)"},
    {"ticker": "CAT-B.ST", "name": "Catella AB (publ)"},
    {"ticker": "CATE.ST", "name": "Catena AB (publ)"},
    {"ticker": "CAVO.ST", "name": "Cavotec Group SA"},
    {"ticker": "CELLAV.ST", "name": "CellaVision AB (publ)"},
    {"ticker": "CIBUS.ST", "name": "Cibus Nordic Real Estate AB (publ)"},
    {"ticker": "CINN.ST", "name": "Cinclus Pharma Holding AB (publ)"},
    {"ticker": "CINT.ST", "name": "Cint Group AB (publ)"},
    {"ticker": "CLAS-B.ST", "name": "Clas Ohlson AB (publ)"},
    {"ticker": "CLOET-B.ST", "name": "Cloetta AB (publ)"},
    {"ticker": "COIN.ST", "name": "CoinShares International Ltd"},
    {"ticker": "COOR.ST", "name": "Coor Service Management Holding AB (publ)"},
    {"ticker": "CORE-A.ST", "name": "Corem Property Group AB (publ)"},
    {"ticker": "CORE-B.ST", "name": "Corem Property Group AB (publ)"},
    {"ticker": "CORE-D.ST", "name": "Corem Property Group AB (publ)"},
    {"ticker": "CORE-PREF.ST", "name": "Corem Property Group AB (publ)"},
    {"ticker": "CRED-A.ST", "name": "Creades AB (publ)"},
    {"ticker": "CTT.ST", "name": "CTT Systems AB (publ)"},
    {"ticker": "DIOS.ST", "name": "Diös Fastigheter AB (publ)"},
    {"ticker": "DOM.ST", "name": "Dometic Group AB (publ)"},
    {"ticker": "DUNI.ST", "name": "Duni AB (publ)"},
    {"ticker": "DUST.ST", "name": "Dustin Group AB (publ)"},
    {"ticker": "DYNA.ST", "name": "Dynavox Group AB (publ)"},
    {"ticker": "EAST.ST", "name": "Eastnine AB (publ)"},
    {"ticker": "ELAN-B.ST", "name": "Elanders AB (publ)"},
    {"ticker": "ELUX-A.ST", "name": "Electrolux AB (publ)"},
    {"ticker": "ELUX-B.ST", "name": "Electrolux AB (publ)"},
    {"ticker": "ELUXB.ST", "name": "Electrolux AB (publ)"},
    {"ticker": "ELUX-PRO-B.ST", "name": "Electrolux Professional AB (publ)"},
    {"ticker": "ELFA-B.ST", "name": "Elekta AB (publ)"},
    {"ticker": "EMBRAC-B.ST", "name": "Embracer Group AB (publ)"},
    {"ticker": "ENEA.ST", "name": "Enea AB (publ)"},
    {"ticker": "ENGCON-B.ST", "name": "engcon AB (publ)"},
    {"ticker": "ENITY.ST", "name": "Enity Holding AB (publ)"},
    {"ticker": "EOLU-B.ST", "name": "Eolus Vind AB (publ)"},
    {"ticker": "EPEN.ST", "name": "Ependion AB (publ)"},
    {"ticker": "EPI-A.ST", "name": "Epiroc AB (publ)"},
    {"ticker": "EPI-B.ST", "name": "Epiroc AB (publ)"},
    {"ticker": "EQT.ST", "name": "EQT AB (publ)"},
    {"ticker": "ERIC-A.ST", "name": "Telefonaktiebolaget LM Ericsson (publ)"},
    {"ticker": "ERIC-B.ST", "name": "Telefonaktiebolaget LM Ericsson (publ)"},
    {"ticker": "ESSITY-A.ST", "name": "Essity AB (publ)"},
    {"ticker": "ESSITY-B.ST", "name": "Essity AB (publ)"},
    {"ticker": "EVO.ST", "name": "Evolution AB (publ)"},
    {"ticker": "EWRK.ST", "name": "Ework Group AB (publ)"},
    {"ticker": "FABG.ST", "name": "Fabege AB (publ)"},
    {"ticker": "FAG.ST", "name": "Fagerhult Group AB (publ)"},
    {"ticker": "FG.ST", "name": "Fasadgruppen Group AB (publ)"},
    {"ticker": "BALD-B.ST", "name": "Fastighets AB Balder (publ)"},
    {"ticker": "EMIL-PREF.ST", "name": "Fastighetsbolaget Emilshus AB (publ)"},
    {"ticker": "EMIL-B.ST", "name": "Fastighetsbolaget Emilshus AB (publ)"},
    {"ticker": "FPAR-A.ST", "name": "Fastpartner AB (publ)"},
    {"ticker": "FPAR-D.ST", "name": "Fastpartner AB (publ)"},
    {"ticker": "FOI-B.ST", "name": "Fenix Outdoor International AG"},
    {"ticker": "FLERIE.ST", "name": "Flerie AB (publ)"},
    {"ticker": "FMM-B.ST", "name": "FM Mattsson Group AB (publ)"},
    {"ticker": "GENO.ST", "name": "Genova Property Group AB (publ)"},
    {"ticker": "GENTOO.ST", "name": "Gentoo Media AB (publ)"},
    {"ticker": "GETI-B.ST", "name": "Getinge AB (publ)"},
    {"ticker": "GREEN.ST", "name": "Green Landscaping Group AB (publ)"},
    {"ticker": "VISC-B.ST", "name": "Gruvaktiebolaget Viscaria AB (publ)"},
    {"ticker": "GRANG.ST", "name": "Gränges AB (publ)"},
    {"ticker": "Hacksaw.ST", "name": "Hacksaw Gaming Holding AB (publ)"},
    {"ticker": "HNSA.ST", "name": "Hansa Biopharma AB (publ)"},
    {"ticker": "HANZA.ST", "name": "HANZA AB (publ)"},
    {"ticker": "HEBA-B.ST", "name": "HEBA Fastighets AB (publ)"},
    {"ticker": "HEM.ST", "name": "Hemnet Group AB (publ)"},
    {"ticker": "HM-B.ST", "name": "Hennes & Mauritz AB (publ)"},
    {"ticker": "HEXA-B.ST", "name": "Hexagon AB (publ)"},
    {"ticker": "HTRO.ST", "name": "Hexatronic Group AB (publ)"},
    {"ticker": "HPOL-B.ST", "name": "HEXPOL AB (publ)"},
    {"ticker": "HMS.ST", "name": "HMS Networks AB (publ)"},
    {"ticker": "HOFI.ST", "name": "Hoist Finance AB (publ)"},
    {"ticker": "HOLM-A.ST", "name": "Holmen AB (publ)"},
    {"ticker": "HOLM-B.ST", "name": "Holmen AB (publ)"},
    {"ticker": "HUFV-A.ST", "name": "Hufvudstaden AB (publ)"},
    {"ticker": "HUM.ST", "name": "Humana AB (publ)"},
    {"ticker": "HUMBLE.ST", "name": "Humble Group AB (publ)"},
    {"ticker": "HUSQ-A.ST", "name": "Husqvarna AB (publ)"},
    {"ticker": "HUSQ-B.ST", "name": "Husqvarna AB (publ)"},
    {"ticker": "IAR.ST", "name": "I.A.R Systems Group AB (publ)"},
    {"ticker": "INDU-A.ST", "name": "Industrivärden AB (publ)"},
    {"ticker": "INDU-C.ST", "name": "Industrivärden AB (publ)"},
    {"ticker": "INDT.ST", "name": "Indutrade AB (publ)"},
    {"ticker": "INSTAL.ST", "name": "Instalco AB (publ)"},
    {"ticker": "INTEA-B.ST", "name": "Intea Fastigheter AB (publ)"},
    {"ticker": "INTEA-D.ST", "name": "Intea Fastigheter AB (publ)"},
    {"ticker": "IPC.ST", "name": "International Petroleum Corp"},
    {"ticker": "INTRUM.ST", "name": "Intrum AB (publ)"},
    {"ticker": "INVE-A.ST", "name": "Investor AB (publ)"},
    {"ticker": "INVE-B.ST", "name": "Investor AB (publ)"},
    {"ticker": "INVI.ST", "name": "INVISIO AB (publ)"},
    {"ticker": "INWI.ST", "name": "Inwido AB (publ)"},
    {"ticker": "ITAB.ST", "name": "ITAB Shop Concept AB (publ)"},
    {"ticker": "JM.ST", "name": "JM AB (publ)"},
    {"ticker": "JOMA.ST", "name": "John Mattson Fastighetsföret"},
    {"ticker": "KFAST-B.ST", "name": "K-Fast Holding AB (publ)"},
    {"ticker": "KABE-B.ST", "name": "KABE Group AB (publ)"},
    {"ticker": "KARN.ST", "name": "Karnov Group AB (publ)"},
    {"ticker": "KINV-A.ST", "name": "Kinnevik AB (publ)"},
    {"ticker": "KINV-B.ST", "name": "Kinnevik AB (publ)"},
    {"ticker": "KBAB-B.ST", "name": "KlaraBo Sverige AB (publ)"},
    {"ticker": "KNOW.ST", "name": "Knowit AB (publ)"},
    {"ticker": "LAG-B.ST", "name": "Lagercrantz Group AB (publ)"},
    {"ticker": "LAT-B.ST", "name": "Latour AB (publ)"},
    {"ticker": "LIFCO-B.ST", "name": "Lifco AB (publ)"},
    {"ticker": "LIME.ST", "name": "Lime Technologies AB (publ)"},
    {"ticker": "LINC.ST", "name": "Linc AB (publ)"},
    {"ticker": "LIAB.ST", "name": "Lindab International AB (publ)"},
    {"ticker": "LOGI-A.ST", "name": "Logistea AB (publ)"},
    {"ticker": "LOGI-B.ST", "name": "Logistea AB (publ)"},
    {"ticker": "LOOM.ST", "name": "Loomis AB (publ)"},
    {"ticker": "LUND-B.ST", "name": "Lundbergföretagen AB (publ)"},
    {"ticker": "LUG.ST", "name": "Lundin Gold Inc."},
    {"ticker": "LUM.ST", "name": "Lundin Mining Corporation"},
    {"ticker": "MCAP.ST", "name": "MedCap AB (publ)"},
    {"ticker": "MCOV-B.ST", "name": "Medicover AB (publ)"},
    {"ticker": "MEKO.ST", "name": "MEKO AB (publ)"},
    {"ticker": "MEREN.ST", "name": "Meren Energy AB (publ)"},
    {"ticker": "MILD.ST", "name": "Mildef Group AB (publ)"},
    {"ticker": "MIPS.ST", "name": "Mips AB (publ)"},
    {"ticker": "MTG-A.ST", "name": "Modern Times Group MTG AB (publ)"},
    {"ticker": "MTG-B.ST", "name": "Modern Times Group MTG AB (publ)"},
    {"ticker": "MMGR-B.ST", "name": "Momentum Group AB (publ)"},
    {"ticker": "MTRS.ST", "name": "Munters Group AB (publ)"},
    {"ticker": "MYCR.ST", "name": "Mycronic AB (publ)"},
    {"ticker": "NCAB.ST", "name": "NCAB Group AB (publ)"},
    {"ticker": "NCC-A.ST", "name": "NCC AB (publ)"},
    {"ticker": "NCC-B.ST", "name": "NCC AB (publ)"},
    {"ticker": "NED-B.ST", "name": "Nederman Holding AB (publ)"},
    {"ticker": "NEOBO.ST", "name": "Neobo Fastigheter AB (publ)"},
    {"ticker": "NETI-B.ST", "name": "Net Insight AB (publ)"},
    {"ticker": "NWG-B.ST", "name": "New Wave Group AB (publ)"},
    {"ticker": "NIBE-B.ST", "name": "NIBE Industrier AB (publ)"},
    {"ticker": "NIVA-B.ST", "name": "Nivika Fastigheter AB (publ)"},
    {"ticker": "NOBI.ST", "name": "Nobia AB (publ)"},
    {"ticker": "NOLA-B.ST", "name": "Nolato AB (publ)"},
    {"ticker": "NDA-SE.ST", "name": "Nordea Bank Abp"},
    {"ticker": "NORD-P.ST", "name": "Nordic Paper Holding AB (publ)"},
    {"ticker": "NNET.ST", "name": "Nordnet AB (publ)"},
    {"ticker": "NORION.ST", "name": "Norion Bank AB (publ)"},
    {"ticker": "NOTE.ST", "name": "NOTE AB (publ)"},
    {"ticker": "NP3.ST", "name": "NP3 Fastigheter AB (publ)"},
    {"ticker": "NP3-PREF.ST", "name": "NP3 Fastigheter AB (publ)"},
    {"ticker": "NYFOSA.ST", "name": "Nyfosa AB (publ)"},
    {"ticker": "OEM-B.ST", "name": "OEM International AB (publ)"},
    {"ticker": "ORRON.ST", "name": "Orrön Energy AB (publ)"},
    {"ticker": "PANDX-B.ST", "name": "Pandox AB (publ)"},
    {"ticker": "PEAB-B.ST", "name": "Peab AB (publ)"},
    {"ticker": "PLAT-B.ST", "name": "Platzer Fastigheter Holding AB (publ)"},
    {"ticker": "POW.ST", "name": "PowerCell Sweden AB (publ)"},
    {"ticker": "PRIC-B.ST", "name": "Pricer AB (publ)"},
    {"ticker": "PRISMA.ST", "name": "Prisma Properties AB (publ)"},
    {"ticker": "PACT.ST", "name": "Proact IT Group AB (publ)"},
    {"ticker": "PRTO.ST", "name": "Profoto Holding AB (publ)"},
    {"ticker": "RATOS-A.ST", "name": "Ratos AB (publ)"},
    {"ticker": "RATOS-B.ST", "name": "Ratos AB (publ)"},
    {"ticker": "RAY-B.ST", "name": "RaySearch Laboratories AB (publ)"},
    {"ticker": "REJL-B.ST", "name": "Rejlers AB (publ)"},
    {"ticker": "RESURS.ST", "name": "Resurs Holding AB (publ)"},
    {"ticker": "ROTT.ST", "name": "Rottneros AB (publ)"},
    {"ticker": "RUSTA.ST", "name": "Rusta AB (publ)"},
    {"ticker": "RVRC.ST", "name": "RVRC Holding AB (publ)"},
    {"ticker": "RÖKO-B.ST", "name": "Röko AB (publ)"},
    {"ticker": "SAAB-B.ST", "name": "SAAB AB (publ)"},
    {"ticker": "SAGA-A.ST", "name": "Sagax AB (publ)"},
    {"ticker": "SAGA-B.ST", "name": "Sagax AB (publ)"},
    {"ticker": "SAGA-D.ST", "name": "Sagax AB (publ)"},
    {"ticker": "SBB-B.ST", "name": "Samhällsbyggnadsbo. i Norden B"},
    {"ticker": "SBB-D.ST", "name": "Samhällsbyggnadsbo. i Norden D"},
    {"ticker": "SAMPO.ST", "name": "Sampo Oyj"},
    {"ticker": "SAND.ST", "name": "Sandvik AB (publ)"},
    {"ticker": "SCA-A.ST", "name": "SCA AB (publ)"},
    {"ticker": "SCA-B.ST", "name": "SCA AB (publ)"},
    {"ticker": "SCS.ST", "name": "Scandi Standard AB (publ)"},
    {"ticker": "SHOT.ST", "name": "Scandic Hotels Group AB (publ)"},
    {"ticker": "SDIP-B.ST", "name": "Sdiptech AB (publ)"},
    {"ticker": "SDIP-PREF.ST", "name": "Sdiptech AB (publ)"},
    {"ticker": "SEB-A.ST", "name": "Skandinaviska Enskilda Banken AB (publ)"},
    {"ticker": "SEB-C.ST", "name": "Skandinaviska Enskilda Banken AB (publ)"},
    {"ticker": "SECT-B.ST", "name": "SECTRA AB (publ)"},
    {"ticker": "SECU-B.ST", "name": "Securitas AB (publ)"},
    {"ticker": "SEDANA.ST", "name": "Sedana Medical AB (publ)"},
    {"ticker": "SINCH.ST", "name": "Sinch AB (publ)"},
    {"ticker": "SKANS-B.ST", "name": "Skanska AB (publ)"},
    {"ticker": "SKF-A.ST", "name": "SKF AB (publ)"},
    {"ticker": "SKF-B.ST", "name": "SKF AB (publ)"},
    {"ticker": "SKIS-B.ST", "name": "SkiStar AB (publ)"},
    {"ticker": "SSAB-A.ST", "name": "SSAB AB (publ)"},
    {"ticker": "SSAB-B.ST", "name": "SSAB AB (publ)"},
    {"ticker": "STEF-B.ST", "name": "Stendörren Fastigheter AB (publ)"},
    {"ticker": "SFAST.ST", "name": "Stenhus Fastigheter i Norden AB (publ)"},
    {"ticker": "STILL.ST", "name": "Stillfront Group AB (publ)"},
    {"ticker": "STE-A.ST", "name": "Stora Enso Oyj"},
    {"ticker": "STE-R.ST", "name": "Stora Enso Oyj"},
    {"ticker": "STOR-B.ST", "name": "Storskogen Group AB (publ)"},
    {"ticker": "SHB-A.ST", "name": "Svenska Handelsbanken AB (publ)"},
    {"ticker": "SHB-B.ST", "name": "Svenska Handelsbanken AB (publ)"},
    {"ticker": "SVEA.ST", "name": "Sveafastigheter AB (publ)"},
    {"ticker": "SVOL-A.ST", "name": "Svolder AB (publ)"},
    {"ticker": "SVOL-B.ST", "name": "Svolder AB (publ)"},
    {"ticker": "SWEC-A.ST", "name": "SWECO AB (publ)"},
    {"ticker": "SWEC-B.ST", "name": "SWECO AB (publ)"},
    {"ticker": "SWED-A.ST", "name": "Swedbank AB (publ)"},
    {"ticker": "SLP-B.ST", "name": "Swedish Logistic Property AB (publ)"},
    {"ticker": "SOBI.ST", "name": "Swedish Orphan Biovitrum AB (publ)"},
    {"ticker": "SYNSAM.ST", "name": "Synsam AB (publ)"},
    {"ticker": "SYSR.ST", "name": "Systemair AB (publ)"},
    {"ticker": "TEL2-A.ST", "name": "Tele2 AB (publ)"},
    {"ticker": "TEL2-B.ST", "name": "Tele2 AB (publ)"},
    {"ticker": "TELIA.ST", "name": "Telia Company AB (publ)"},
    {"ticker": "TFBANK.ST", "name": "TF Bank AB (publ)"},
    {"ticker": "THULE.ST", "name": "Thule Group AB (publ)"},
    {"ticker": "TIETO.ST", "name": "TietoEVRY Oyj"},
    {"ticker": "TRAC-B.ST", "name": "Traction AB (publ)"},
    {"ticker": "TRATON.ST", "name": "TRATON SE"},
    {"ticker": "TREL-B.ST", "name": "Trelleborg AB (publ)"},
    {"ticker": "TRIAN-B.ST", "name": "Trianon AB (publ)"},
    {"ticker": "TROAX.ST", "name": "Troax Group AB (publ)"},
    {"ticker": "TRUE-B.ST", "name": "Truecaller AB (publ)"},
    {"ticker": "VBG-B.ST", "name": "VBG GROUP AB (publ)"},
    {"ticker": "VEF.ST", "name": "VEF Ltd"},
    {"ticker": "VESTUM.ST", "name": "Vestum AB (publ)"},
    {"ticker": "VPLAY-A.ST", "name": "Viaplay Group AB (publ)"},
    {"ticker": "VPLAY-B.ST", "name": "Viaplay Group AB (publ)"},
    {"ticker": "VIMIAN.ST", "name": "Vimian Group AB (publ)"},
    {"ticker": "VITEC-B.ST", "name": "Vitec Software Group AB (publ)"},
    {"ticker": "VITR.ST", "name": "Vitrolife AB (publ)"},
    {"ticker": "VNV.ST", "name": "VNV Global Ltd"},
    {"ticker": "VOLO.ST", "name": "Volati AB (publ)"},
    {"ticker": "VOLO-PREF.ST", "name": "Volati AB (publ) Pref"},
    {"ticker": "VOLV-A.ST", "name": "Volvo AB (publ)"},
    {"ticker": "VOLV-B.ST", "name": "Volvo AB (publ)"},
    {"ticker": "VOLCAR-B.ST", "name": "Volvo Car AB (publ)"},
    {"ticker": "WALL-B.ST", "name": "Wallenstam AB (publ)"},
    {"ticker": "WIHL.ST", "name": "Wihlborgs Fastigheter AB (publ)"},
    {"ticker": "XANO-B.ST", "name": "XANO Industri AB (publ)"},
    {"ticker": "XVIVO.ST", "name": "Xvivo Perfusion AB (publ)"},
    {"ticker": "YUBICO.ST", "name": "Yubico AB (publ)"},
]

@app.route('/api/stocks/names', methods=['GET'])
def get_all_stock_names():
    """Returnerar en statisk lista med alla tickers och deras longName."""
    return jsonify(tickers)


@app.route('/api/stocks/details/<ticker>', methods=['GET'])
def get_stock_details(ticker):
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        
        hist_data = stock.history(period="1d", interval="5m")

        if not hist_data.empty:
            price_history = hist_data['Close'].dropna().tolist()
        else:
            price_history = []

        price = info.get("regularMarketPrice")
        name = info.get("longName")
        change_raw = info.get("regularMarketChange")

        if change_raw is not None:
            change = round(float(change_raw), 2)
        else:
            change = None

        currency = info.get("currency")

        return jsonify({
            "ticker": ticker,
            "name": name,
            "change": change,
            "price": round(float(price), 2) if price is not None else None,
            "currency": currency,
            "metrics": {
                "market_cap": info.get("marketCap"),
                "enterprise_value": info.get("enterpriseValue"),
                "trailing_pe": info.get("trailingPE"),
                "forward_pe": info.get("forwardPE"),
                "peg_ratio": info.get("pegRatio"),
                "ps_ratio": info.get("priceToSalesTrailing12Months"),
                "pb_ratio": info.get("priceToBook"),
                "ev_revenue": info.get("enterpriseToRevenue"),
                "ev_ebitda": info.get("enterpriseToEbitda")
            },
            "priceHistory": price_history
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    # Get the port from the environment, defaulting to 5000
    port = int(os.environ.get("PORT", 5000))
    # Run the app, binding to 0.0.0.0 to accept external requests
    app.run(host='0.0.0.0', port=port, debug=True)








# const stockholmLargeMidCap = [
#   "AAK.ST",
#   "ABB.ST",
#   "ACAD.ST",
#   "ALIF-B.ST",
#   "ANOD-B.ST",
#   "ADDT-B.ST",
#   "AFRY.ST",
#   "ALFA.ST",
#   "ALIG.ST"
#   "ALLEI.ST",
#   "ALLIGO-B.ST",
#   "ALVO-SDB.ST",
#   "AMBEA.ST",
#   "APOTEA.ST",
#   "AQ.ST",
#   "ARP.ST"
#   "ARION-SDB.ST",
#   "ARISE.ST",
#   "ARJO-B.ST",
#   "ASKER.ST",
#   "ASMDEE-B.ST",
#   "ASSA-B.ST",
#   "AZN.ST",
 #  ATCO-A.ST
#   ATCO-B.ST",
#   "ATRLJ-B.ST",
#   "ATT.ST",
#   "ALIV-SDB.ST",
#   "AZA.ST",
#   "AXFO.ST",
#   "BACTI-B.ST",
#   "BEIA-B.ST",
#   "BEIJ-B.ST",
#   "BERG-B.ST",
#   "BESQAB.ST",
#   "BESQAB-PREF-B.ST",
#   "BETS-B.ST",
#   "BETCO.ST",
#   "BHG.ST",
#   "BICO.ST",
#   "BILI-A.ST",
#   "BILL.ST",
#   "BIOA-B.ST",
#   "BIOG-B.ST",
#   "BINV.ST",
#   "BOL.ST",
#   "BONAV-A.ST",
#   "BONAV-B.ST",
#   "BONEX.ST",
#   "BOOZT.ST",
#   "BRAV.ST",
#   "BRIN-B.ST",
#   "BTS-B.ST",
#   "BUFAB.ST",




#   "Bure Equity",
#   "Byggmax Group",
#   "Byggmästare A J Ahlström H",
#   "Camurus",
#   "Castellum",
#   "Catella A",
#   "Catella B",



#   "Catena",
#   "Cavotec Group",
#   "CellaVision",
#   "Cibus Nordic Real Estate",
#   "Cinclus Pharma Holding",
#   "Cint Group",
#   "Clas Ohlson B",
#   "Cloetta B",
#   "CoinShares International",
#   "Coor Service Management Hold",
#   "Corem Property Group A",
#   "Corem Property Group B",
#   "Corem Property Group D",
#   "Corem Property Group Pref",
#   "Creades A",
#   "CTT Systems",
#   "Diös Fastigheter",
#   "Dometic Group",
#   "Duni",
#   "Dustin Group",
#   "Dynavox Group",
#   "Eastnine",
#   "Elanders B",
#   "Electrolux A",
#   "Electrolux B",
#   "Electrolux Professional B",
#   "Elekta B",
#   "Embracer Group B",
#   "Enea",
#   "engcon B",
#   "Enity Holding",
#   "Eolus B",
#   "Ependion",
#   "Epiroc A",
#   "Epiroc B",
#   "EQT",
#   "Ericsson A",
#   "Ericsson B",
#   "Essity A",
#   "Essity B",
#   "Evolution",
#   "Ework Group",
#   "Fabege",
#   "Fagerhult Group",
#   "Fasadgruppen Group",
#   "Fast. Balder B",
#   "Fastighetsbolag. Emilshus Pref",
#   "Fastighetsbolaget Emilshus B",
#   "Fastpartner A",
#   "Fastpartner D",
#   "Fenix Outdoor International B",
#   "Flerie",
#   "FM Mattsson B",
#   "Genova Property Group",
#   "Gentoo Media",
#   "Getinge B",
#   "Green Landscaping Group",
#   "Gruvaktiebolaget Viscaria",
#   "Gränges",
#   "Hacksaw",
#   "Hansa Biopharma",
#   "HANZA",
#   "HEBA B",
#   "Hemnet Group",
#   "Hennes & Mauritz B",
#   "Hexagon B",
#   "Hexatronic Group",
#   "HEXPOL B",
#   "HMS Networks",
#   "Hoist Finance",
#   "Holmen A",
#   "Holmen B",
#   "Hufvudstaden A",
#   "Humana",
#   "Humble Group",
#   "Husqvarna A",
#   "Husqvarna B",
#   "I.A.R Systems Group",
#   "Industrivärden A",
#   "Industrivärden C",
#   "Indutrade",
#   "Instalco",
#   "Intea Fastigheter B",
#   "Intea Fastigheter D",
#   "International Petroleum Corp",
#   "Intrum",
#   "Investor A",
#   "Investor B",
#   "INVISIO",
#   "Inwido",
#   "ITAB Shop Concept",
#   "JM",
#   "John Mattson Fastighetsföret",
#   "K-Fast Holding B",
#   "KABE Group B",
#   "Karnov Group",
#   "Kinnevik A",
#   "Kinnevik B",
#   "KlaraBo Sverige B",
#   "Knowit",
#   "Lagercrantz Group B",
#   "Latour B",
#   "Lifco B",
#   "Lime Technologies",
#   "Linc",
#   "Lindab International",
#   "Logistea A",
#   "Logistea B",
#   "Loomis",
#   "Lundbergföretagen B",
#   "Lundin Gold",
#   "Lundin Mining Corporation",
#   "MedCap",
#   "Medicover B",
#   "MEKO",
#   "Meren Energy",
#   "Mildef Group",
#   "Mips",
#   "Modern Times Group A",
#   "Modern Times Group B",
#   "Momentum Group B",
#   "Munters Group",
#   "Mycronic",
#   "NCAB Group",
#   "NCC A",
#   "NCC B",
#   "Nederman Holding",
#   "Neobo Fastigheter",
#   "Net Insight B",
#   "New Wave B",
#   "NIBE Industrier B",
#   "Nivika Fastigheter B",
#   "Nobia",
#   "Nolato B",
#   "Nordea Bank Abp",
#   "Nordic Paper Holding",
#   "Nordnet",
#   "Norion Bank",
#   "NOTE",
#   "NP3 Fastigheter",
#   "NP3 Fastigheter Pref",
#   "Nyfosa",
#   "OEM International B",
#   "Orrön Energy",
#   "Pandox B",
#   "Peab B",
#   "Platzer Fastigheter Holding B",
#   "PowerCell Sweden",
#   "Pricer B",
#   "Prisma Properties",
#   "Proact IT Group",
#   "Profoto Holding",
#   "Ratos A",
#   "Ratos B",
#   "RaySearch Laboratories B",
#   "Rejlers B",
#   "Resurs Holding",
#   "Rottneros",
#   "Rusta",
#   "RVRC Holding",
#   "Röko B",
#   "SAAB B",
#   "Sagax A",
#   "Sagax B",
#   "Sagax D",
#   "Samhällsbyggnadsbo. i Norden B",
#   "Samhällsbyggnadsbo. i Norden D",
#   "Sampo Oyj SDB",
#   "Sandvik",
#   "SCA A",
#   "SCA B",
#   "Scandi Standard",
#   "Scandic Hotels Group",
#   "Sdiptech B",
#   "Sdiptech Pref",
#   "SEB A",
#   "SEB C",
#   "SECTRA B",
#   "Securitas B",
#   "Sedana Medical",
#   "Sinch",
#   "Skanska B",
#   "SKF A",
#   "SKF B",
#   "SkiStar B",
#   "SSAB A",
#   "SSAB B",
#   "Stendörren Fastigheter B",
#   "Stenhus Fastigheter i Norden",
#   "Stillfront Group",
#   "Stora Enso A",
#   "Stora Enso R",
#   "Storskogen Group B",
#   "Sv. Handelsbanken A",
#   "Sv. Handelsbanken B",
#   "Sveafastigheter",
#   "Svolder A",
#   "Svolder B",
#   "SWECO A",
#   "SWECO B",
#   "Swedbank A",
#   "Swedish Logistic Property B",
#   "Swedish Orphan Biovitrum",
#   "Synsam",
#   "Systemair",
#   "Tele2 A",
#   "Tele2 B",
#   "Telia Company",
#   "TF Bank",
#   "Thule Group",
#   "TietoEVRY Oyj",
#   "Traction B",
#   "TRATON",
#   "Trelleborg B",
#   "Trianon B",
#   "Troax Group",
#   "Truecaller B",
#   "VBG GROUP B",
#   "VEF",
#   "Vestum",
#   "Viaplay Group A",
#   "Viaplay Group B",
#   "Vimian Group",
#   "Vitec Software Group B",
#   "Vitrolife",
#   "VNV Global",
#   "Volati",
#   "Volati Pref",
#   "Volvo A",
#   "Volvo B",
#   "Volvo Car B",
#   "Wallenstam B",
#   "Wihlborgs Fastigheter",
#   "XANO Industri B",
#   "Xvivo Perfusion",
#   "Yubico",
#   "Öresund"
# ];























													